name = "cf-error-explainer"
main = "worker.js"
compatibility_date = "2026-06-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "QUOTA"
id = "8581e701072c40d9bd8e5e23314cbdab"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "9c2c0ac044e2465a8e5c23a23f91a1b6"
